#!/usr/bin/python

"""
Ethernet port speed and port mode type Poller script.

Poller script determines the radwin port speed and port mode.
poller script takes the snmp value of OID .1.3.6.1.4.1.4458.1000.1.5.58.0 from snmp agent of device at specific interval.
Ethernet port speed and port status information is sent to device application 

"""
############################################################################
# Function : check_radwin_mimo_diversity_invent
#
# Parameters: info (SNMP output , _no_params ( No parameters))
#
# Output:   service state ,plugin output
###########################################################################


def check_radwin_mimo_diversity_invent(item, _no_params, info):
        try:
		transmission_type  = int(info[0][0])
		if transmission_type == 1:
			type_trans = "Mimo"
			state = 0
		elif transmission_type == 2:
			type_trans = "Diversity"
			state = 0
		else:
			type_trans = "unknown value"
			state = 0 
        	infotext = "%s" % type_trans
	except ValueError:
		state = 0
                infotext = "type mismatch value"
		return(state,infotext)
	except:
		state = 3
		infotext = "Unknown Value"
		return(state,infotext)
        return (state,  infotext)

check_info["radwin_mimo_diversity_invent"] = {
    'check_function'        :  check_radwin_mimo_diversity_invent,
    'service_description'   :  'radwin_mimo_diversity_invent',
}
################################################################################
#	SNMP OID
#################################################################################
snmp_info["radwin_mimo_diversity_invent"] = ( ".1.3.6.1.4.1.4458.1000.1.5", [ "58.0" ] )


