#!/usr/bin/python

def check_radwin_producttype_invent(item, _no_params, info):
        try:
		product_type  = info[0][0]
        	state = 0
        	infotext = "%s" % product_type
	except:
		state = 3
		infotext = "Unknown value"
        return (state,  infotext)

check_info["radwin_producttype_invent"] = {
    'check_function'        :  check_radwin_producttype_invent,
    'service_description'   :  'radwin_producttype_invent',
}

snmp_info["radwin_producttype_invent"] = ( ".1.3.6.1.4.1.4458.1000.1", [ "1.30" ] )
#snmp_info["radwin_producttype_invent"] = ( ".1.3.6.1.4.1.4458.1000.1", [ "5.8" ] )

