#!/usr/bin/python

params = (-50,-80)
def check_radwin_rssi(item,params,info):
	try:
		warn ,crit = params
        	rssi  = int(info[0][0])
		if rssi < crit:
			state = 2
		elif rssi > crit and rssi < warn:
			state = 1
		else:
			state =0
	except:
		print radwin_ssi_parameters
	infotext = "Device received signal strength indication is %s " % rssi
        return (state,  infotext, [("radwin_rssi",rssi,warn,crit)])

check_info["radwin_rssi"] = {
	'check_function'        :  check_radwin_rssi,
	'service_description'   :  'Radwin_rssi',
	'has_perfdata'          :  True,
}

snmp_info["radwin_rssi"] = ( ".1.3.6.1.4.1.4458.1000.1.6.4.1", [ "1.101" ] )
#snmp_info["radwin_rssi"] = ( ".1.3.6.1.4.1.4458.1000.1", [ "5.8" ] )
