#!/usr/bin/python

def check_radwin_utilization(item, _no_params, info):
        utilization  = info[0][0]
        state = 0
        infotext = "Device utilization is %d " % utilization
        return (state,  infotext)

check_info["radwin_utilization"] = {
    'check_function'        :  check_radwin_utilization,
    'service_description'   :  'Radwin_utilization',
}

snmp_info["radwin_utilization"] = ( ".1.3.6.1.4.1.4458.1000.2.2", [ "14.0" ] )
#snmp_info["radwin_utilization"] = ( ".1.3.6.1.4.1.4458.1000.1", [ "5.8" ] )
