#!/usr/bin/python

def check_radwin_ssid_invent(item, _no_params, info):
        try:
		if info[0][0]:
			ssid  = info[0][0]
        		state = 0
        		infotext = "%s" % ssid
	except:
		state = 3
		infotext = "Unknown value"
		ssid = None
		return (state,infotext)
        return (state,  infotext)

check_info["radwin_ssid_invent"] = {
    'check_function'        :  check_radwin_ssid_invent,
    'service_description'   :  'radwin_ssid_invent',
}

snmp_info["radwin_ssid_invent"] = ( ".1.3.6.1.4.1.4458.1000.1", [ "5.3" ] )
#snmp_info["radwin_mimo_diversity"] = ( ".1.3.6.1.4.1.4458.1000.1", [ "5.8" ] )

