#!/usr/bin/python

def check_radwin_mimo_diversity_invent(item, _no_params, info):
        try:
		transmission_type  = int(info[0][0])
		if transmission_type == 1:
			type_trans = "Mimo"
		elif transmission_type == 2:
			type_trans = "Diversity"
		state = 0
        	infotext = "%s" % str(type_trans)
	except:
		state = 3
		infotext = "Unkown output"
        return (state,  infotext)

check_info["radwin_mimo_diversity_invent"] = {
    'check_function'        :  check_radwin_mimo_diversity_invent,
    'service_description'   :  'radwin_mimo_diversity_invent',
}

#snmp_info["radwin_mimo_diversity_invent"] = ( ".1.3.6.1.2.1.2.2.1", [ "7.1" ] )
snmp_info["radwin_mimo_diversity_invent"] = ( ".1.3.6.1.4.1.4458.1000.1.5", [ "58.0" ] )


