#!/usr/bin/python

"""
SS ID Poller script.

Poller script determines the SS id.
poller script takes the snmp value of OID .1.3.6.1.4.1.4458.1000.2.2.14.0 from snmp agent of device at specific interval.
SS ID information is sent to device application 


"""
##############################################################
# Function : check_radwin_service_throughput
#
# Parameters : info (SNMP output), _no_params (scripts params)
#
# Output:   service state,plugin output ,peformance data
###############################################################



def check_radwin_service_throughput(item, _no_params, info):
	try:
		service_throughput  = int(info[0][0])
		if service_throughput == 0 or service_throughput < -1:
			state = 0
			infotext = "Device service throughput is Zero or negative" 
		else:
			state = 0
			infotext = "Device service_throughput is %d " % service_throughput
	except ValueError:
		state = 0
		infotext = "type mismatch value"
		service_throughput = None
		return (state,infotext,[("Service_throughput",service_throughput)])
	except:
		state = 3
		infotext = "unknown value"
		service_throughput = None	
	return (state,  infotext,[("Service_throughput",service_throughput)])

check_info["radwin_service_throughput"] = {
	'check_function'        :  check_radwin_service_throughput,
	'service_description'   :  'radwin_service_throughput',
	'has_perfdata'		:  True,
	
}

#################################################################################
#		SNMP OID
#################################################################################
snmp_info["radwin_service_throughput"] = ( ".1.3.6.1.4.1.4458.1000.2.2", [ "14.0" ] )
