#!/usr/bin/python

def check_radwin_uas(item, _no_params, info):
        try:
		uas  = int(info[0][0])
        	state = 0
        	infotext = "Device uas is %d " % uas
	except:
		state = 3
		infotext = " Snmp timeout for device"
        return (state,  infotext,[("Uas",uas)])

check_info["radwin_uas"] = {
	'check_function'        :  check_radwin_uas,
	'service_description'   :  'Radwin_unavilable_seconds',
	'has_perfdata'		:	True,
}

snmp_info["radwin_uas"] = ( ".1.3.6.1.4.1.4458.1000.1.6.1.1", [ "1.1" ] )
#snmp_info["radwin_uas"] = ( ".1.3.6.1.4.1.4458.1000.1", [ "5.8" ] )

