#!/usr/bin/python

def check_radwin_uas(item, _no_params, info):
        try:
		if info[0][0]:
			uas  = int(info[0][0])
        		state = 0
        		infotext = "Device uas is %d " % uas
	except ValueError:
		state = 0
		infotext = " type mismatch on value"
		uas = None
		return (state,infotext,[("uas",uas)])
	except:
		state = 3
		infotext = "unknown value"
		uas = None
		return (state,infotext,[("uas",uas)])
        return (state,  infotext,[("Uas",uas)])

check_info["radwin_uas"] = {
	'check_function'        :  check_radwin_uas,
	'service_description'   :  'radwin_unavilable_seconds',
	'has_perfdata'		:	True,
}

snmp_info["radwin_uas"] = ( ".1.3.6.1.4.1.4458.1000.1.6.1.1", [ "1.1" ] )
#snmp_info["radwin_uas"] = ( ".1.3.6.1.4.1.4458.1000.1", [ "5.8" ] )

